"""add tenant_id to branches

Revision ID: 2261785f29c7
Revises: 
Create Date: 2026-04-14 15:00:44.910741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2261785f29c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_table('customers')
    op.add_column('branches', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.alter_column('branches', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('branches', 'brand_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('branches', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('branches_code_key'), 'branches', type_='unique')
    op.drop_index(op.f('ix_branches_id'), table_name='branches')
    op.create_foreign_key(None, 'branches', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('branches', 'created_at')
    op.drop_column('branches', 'code')
    op.drop_constraint(op.f('brands_slug_key'), 'brands', type_='unique')
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.create_unique_constraint('uq_brand_slug_per_tenant', 'brands', ['tenant_id', 'slug'])
    op.create_foreign_key(None, 'brands', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'categories', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'items', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'pricings', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'staff', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('tables', 'shape',
               existing_type=postgresql.ENUM('rectangular', 'round', 'square', 'oval', name='tableshape'),
               type_=sa.Enum('rectangular', 'round', 'square', 'oval', name='tableshape', schema='public'),
               existing_nullable=True)
    op.create_foreign_key(None, 'tables', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tables', type_='foreignkey')
    op.alter_column('tables', 'shape',
               existing_type=sa.Enum('rectangular', 'round', 'square', 'oval', name='tableshape', schema='public'),
               type_=postgresql.ENUM('rectangular', 'round', 'square', 'oval', name='tableshape'),
               existing_nullable=True)
    op.drop_constraint(None, 'staff', type_='foreignkey')
    op.drop_constraint(None, 'pricings', type_='foreignkey')
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint(None, 'brands', type_='foreignkey')
    op.drop_constraint('uq_brand_slug_per_tenant', 'brands', type_='unique')
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    op.create_unique_constraint(op.f('brands_slug_key'), 'brands', ['slug'], postgresql_nulls_not_distinct=False)
    op.add_column('branches', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('branches', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'branches', type_='foreignkey')
    op.create_index(op.f('ix_branches_id'), 'branches', ['id'], unique=False)
    op.create_unique_constraint(op.f('branches_code_key'), 'branches', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('branches', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('branches', 'brand_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('branches', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('branches', 'tenant_id')
    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('brand_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('total_orders', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_spent', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('customers_branch_id_fkey')),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('customers_brand_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('customers_pkey'))
    )
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=True)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    # ### end Alembic commands ###
