"""sync models

Revision ID: 402449345b4d
Revises: d41a89bad5f0
Create Date: 2026-06-01 17:45:17.887025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '402449345b4d'
down_revision: Union[str, Sequence[str], None] = 'd41a89bad5f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_legal_compliances_id'), table_name='legal_compliances')
    op.drop_table('legal_compliances')
    op.alter_column('categories', 'branch_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('staff', 'branch_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff', 'branch_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('categories', 'branch_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('legal_compliances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gst_vat_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fssai_license_no', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('legal_compliances_branch_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('legal_compliances_pkey')),
    sa.UniqueConstraint('branch_id', name=op.f('legal_compliances_branch_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_legal_compliances_id'), 'legal_compliances', ['id'], unique=False)
    # ### end Alembic commands ###
