"""add unique constraint to pricing

Revision ID: 610d85ea3cbb
Revises: f7e7555c2d48
Create Date: 2026-04-14 15:17:41.260485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '610d85ea3cbb'
down_revision: Union[str, Sequence[str], None] = 'f7e7555c2d48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_item_per_tenant', 'pricings', ['tenant_id', 'item_id'])
    op.alter_column('tables', 'shape',
               existing_type=postgresql.ENUM('rectangular', 'round', 'square', 'oval', name='tableshape'),
               type_=sa.Enum('rectangular', 'round', 'square', 'oval', name='tableshape', schema='public'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tables', 'shape',
               existing_type=sa.Enum('rectangular', 'round', 'square', 'oval', name='tableshape', schema='public'),
               type_=postgresql.ENUM('rectangular', 'round', 'square', 'oval', name='tableshape'),
               existing_nullable=True)
    op.drop_constraint('unique_item_per_tenant', 'pricings', type_='unique')
    # ### end Alembic commands ###
