"""fix inventory

Revision ID: b55b3188c838
Revises: fe6fdab183cd
Create Date: 2026-04-24 16:55:05.328330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b55b3188c838'
down_revision: Union[str, Sequence[str], None] = 'fe6fdab183cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None




def upgrade():
    op.add_column('clients', sa.Column('role', sa.String(), nullable=True))

def downgrade():
    op.drop_column('clients', 'role')

# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.execute("DROP TABLE orders CASCADE")
#     op.drop_index(op.f('ix_customers_id'), table_name='customers')
#     op.drop_index(op.f('ix_customers_phone'), table_name='customers')
#     op.drop_table('customers')
#     op.drop_table('order_items')
#     op.drop_table('inventory_items')
#     op.alter_column('tables', 'shape',
#                existing_type=postgresql.ENUM('rectangular', 'round', 'square', 'oval', name='tableshape'),
#                type_=sa.Enum('rectangular', 'round', 'square', 'oval', name='tableshape', schema='public'),
#                existing_nullable=True)
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('tables', 'shape',
#                existing_type=sa.Enum('rectangular', 'round', 'square', 'oval', name='tableshape', schema='public'),
#                type_=postgresql.ENUM('rectangular', 'round', 'square', 'oval', name='tableshape'),
#                existing_nullable=True)
#     op.create_table('inventory_items',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
#     sa.Column('row_category', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('stock_qty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
#     sa.Column('reorder_level', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
#     sa.Column('cost_per_unit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
#     sa.Column('vendor_name', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('vendor_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('last_restocked', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
#     sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('inventory_items_branch_id_fkey')),
#     sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('inventory_items_tenant_id_fkey')),
#     sa.PrimaryKeyConstraint('id', name=op.f('inventory_items_pkey'))
#     )
#     op.create_table('order_items',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('order_items_item_id_fkey')),
#     sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('order_items_order_id_fkey')),
#     sa.PrimaryKeyConstraint('id', name=op.f('order_items_pkey'))
#     )
#     op.create_table('customers',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
#     sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
#     sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
#     sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('branch_name', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('customers_branch_id_fkey')),
#     sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('customers_tenant_id_fkey')),
#     sa.PrimaryKeyConstraint('id', name=op.f('customers_pkey')),
#     sa.UniqueConstraint('phone', 'tenant_id', name=op.f('uq_customer_phone_per_tenant'), postgresql_include=[], postgresql_nulls_not_distinct=False)
#     )
#     op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
#     op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
#     op.create_table('orders',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('table_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('order_type', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('customer_name', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('customer_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
#     sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
#     sa.Column('total_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('orders_branch_id_fkey')),
#     sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name=op.f('orders_table_id_fkey')),
#     sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('orders_tenant_id_fkey')),
#     sa.PrimaryKeyConstraint('id', name=op.f('orders_pkey'))
#     )
#     # ### end Alembic commands ###
