"""Add column in table photo

Revision ID: b6245490f67f
Revises: 285a32d3bf06
Create Date: 2026-04-18 14:43:51.865984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6245490f67f'
down_revision: Union[str, Sequence[str], None] = '285a32d3bf06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_table('customers')
    op.drop_column('staff', 'employee_id')
    op.alter_column('tables', 'shape',
               existing_type=postgresql.ENUM('rectangular', 'round', 'square', 'oval', name='tableshape'),
               type_=sa.Enum('rectangular', 'round', 'square', 'oval', name='tableshape', schema='public'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tables', 'shape',
               existing_type=sa.Enum('rectangular', 'round', 'square', 'oval', name='tableshape', schema='public'),
               type_=postgresql.ENUM('rectangular', 'round', 'square', 'oval', name='tableshape'),
               existing_nullable=True)
    op.add_column('staff', sa.Column('employee_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('branch_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('customers_branch_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('customers_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('customers_pkey')),
    sa.UniqueConstraint('phone', 'tenant_id', name=op.f('uq_customer_phone_per_tenant'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    # ### end Alembic commands ###
