"""remove brand_id from tables

Revision ID: bc758c992569
Revises: 9b44bd1d1bc8
Create Date: 2026-05-19 15:17:45.713078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc758c992569'
down_revision: Union[str, Sequence[str], None] = '9b44bd1d1bc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'order_items', 'items', ['item_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'tables', ['table_id'], ['id'])
    op.create_foreign_key(None, 'pricings', 'items', ['item_id'], ['id'])
    op.drop_constraint(op.f('tables_brand_id_fkey'), 'tables', type_='foreignkey')
    op.drop_column('tables', 'brand_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('brand_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('tables_brand_id_fkey'), 'tables', 'brands', ['brand_id'], ['id'])
    op.drop_constraint(None, 'pricings', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    # ### end Alembic commands ###
