"""add_pricing_cost_discount_tax_calories

Revision ID: d12848bf5d4a
Revises: bc758c992569
Create Date: 2026-05-20 12:54:31.479825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd12848bf5d4a'
down_revision: Union[str, Sequence[str], None] = 'bc758c992569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricings', sa.Column('cost_price', sa.Float(), nullable=True))
    op.add_column('pricings', sa.Column('discount', sa.Float(), nullable=True))
    op.add_column('pricings', sa.Column('tax_rate', sa.Float(), nullable=True))
    op.add_column('pricings', sa.Column('calories', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pricings', 'calories')
    op.drop_column('pricings', 'tax_rate')
    op.drop_column('pricings', 'discount')
    op.drop_column('pricings', 'cost_price')
    # ### end Alembic commands ###
