"""remove brand_id from tables

Revision ID: dae6b2992946
Revises: 9b44bd1d1bc8
Create Date: 2026-05-19 14:51:56.430933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dae6b2992946'
down_revision: Union[str, Sequence[str], None] = '9b44bd1d1bc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('orders')
    op.drop_table('order_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_staff_permissions_id'), table_name='staff_permissions')
    op.drop_table('staff_permissions')
    op.create_foreign_key(None, 'pricings', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###


def upgrade():
    pass
    # op.drop_column('tables', 'brand_id')


def downgrade():
    op.add_column(
        'tables',
        sa.Column('brand_id', sa.Integer(), nullable=False)
    )