"""role field

Revision ID: e0d9dbdb137b
Revises: b55b3188c838
Create Date: 2026-05-02 12:30:04.486702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0d9dbdb137b'
down_revision: Union[str, Sequence[str], None] = 'b55b3188c838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade():
    op.add_column('clients', sa.Column('role', sa.String(), nullable=True))

def downgrade():
    op.drop_column('clients', 'role')


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_table('inventory_items')
#     op.drop_table('orders')
#     op.drop_index(op.f('ix_customers_id'), table_name='customers')
#     op.drop_index(op.f('ix_customers_phone'), table_name='customers')
#     op.drop_table('customers')
#     op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
#     op.drop_table('tenants')
#     op.drop_index(op.f('ix_admin_email'), table_name='admin')
#     op.drop_table('admin')
#     op.drop_table('order_items')
#     op.add_column('branches', sa.Column('client_id', sa.Integer(), nullable=False))
#     op.drop_constraint(op.f('branches_tenant_id_fkey'), 'branches', type_='foreignkey')
#     op.create_foreign_key(None, 'branches', 'clients', ['client_id'], ['id'])
#     op.drop_column('branches', 'tenant_id')
#     op.add_column('brands', sa.Column('client_id', sa.Integer(), nullable=False))
#     op.drop_constraint(op.f('uq_brand_slug_per_tenant'), 'brands', type_='unique')
#     op.create_unique_constraint('uq_brand_slug_per_client', 'brands', ['client_id', 'slug'])
#     op.drop_constraint(op.f('brands_tenant_id_fkey'), 'brands', type_='foreignkey')
#     op.create_foreign_key(None, 'brands', 'clients', ['client_id'], ['id'])
#     op.drop_column('brands', 'tenant_id')
#     op.add_column('categories', sa.Column('client_id', sa.Integer(), nullable=True))
#     op.drop_constraint(op.f('categories_tenant_id_fkey'), 'categories', type_='foreignkey')
#     op.create_foreign_key(None, 'categories', 'clients', ['client_id'], ['id'])
#     op.drop_column('categories', 'tenant_id')
#     op.add_column('clients', sa.Column('role', sa.String(), nullable=True))
#     op.add_column('items', sa.Column('client_id', sa.Integer(), nullable=False))
#     op.drop_index(op.f('ix_items_tenant_id'), table_name='items')
#     op.drop_constraint(op.f('uq_item_name_per_tenant'), 'items', type_='unique')
#     op.create_index(op.f('ix_items_client_id'), 'items', ['client_id'], unique=False)
#     op.create_unique_constraint('uq_item_name_per_client', 'items', ['name', 'client_id'])
#     op.drop_constraint(op.f('items_tenant_id_fkey'), 'items', type_='foreignkey')
#     op.create_foreign_key(None, 'items', 'clients', ['client_id'], ['id'])
#     op.drop_column('items', 'tenant_id')
#     op.add_column('pricings', sa.Column('client_id', sa.Integer(), nullable=False))
#     op.drop_constraint(op.f('pricings_tenant_id_fkey'), 'pricings', type_='foreignkey')
#     op.create_foreign_key(None, 'pricings', 'clients', ['client_id'], ['id'])
#     op.drop_column('pricings', 'tenant_id')
#     op.add_column('staff', sa.Column('branch_id', sa.Integer(), nullable=False))
#     op.drop_constraint(op.f('staff_tenant_id_fkey'), 'staff', type_='foreignkey')
#     op.create_foreign_key(None, 'staff', 'branches', ['branch_id'], ['id'])
#     op.drop_column('staff', 'tenant_id')
#     op.add_column('tables', sa.Column('client_id', sa.Integer(), nullable=False))
#     op.alter_column('tables', 'shape',
#                existing_type=postgresql.ENUM('rectangular', 'round', 'square', 'oval', name='tableshape'),
#                type_=sa.Enum('rectangular', 'round', 'square', 'oval', name='tableshape', schema='public'),
#                existing_nullable=True)
#     op.drop_constraint(op.f('tables_tenant_id_fkey'), 'tables', type_='foreignkey')
#     op.create_foreign_key(None, 'tables', 'clients', ['client_id'], ['id'])
#     op.drop_column('tables', 'tenant_id')
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('tables', sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False))
#     op.drop_constraint(None, 'tables', type_='foreignkey')
#     op.create_foreign_key(op.f('tables_tenant_id_fkey'), 'tables', 'tenants', ['tenant_id'], ['id'])
#     op.alter_column('tables', 'shape',
#                existing_type=sa.Enum('rectangular', 'round', 'square', 'oval', name='tableshape', schema='public'),
#                type_=postgresql.ENUM('rectangular', 'round', 'square', 'oval', name='tableshape'),
#                existing_nullable=True)
#     op.drop_column('tables', 'client_id')
#     op.add_column('staff', sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True))
#     op.drop_constraint(None, 'staff', type_='foreignkey')
#     op.create_foreign_key(op.f('staff_tenant_id_fkey'), 'staff', 'tenants', ['tenant_id'], ['id'])
#     op.drop_column('staff', 'branch_id')
#     op.add_column('pricings', sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False))
#     op.drop_constraint(None, 'pricings', type_='foreignkey')
#     op.create_foreign_key(op.f('pricings_tenant_id_fkey'), 'pricings', 'tenants', ['tenant_id'], ['id'])
#     op.drop_column('pricings', 'client_id')
#     op.add_column('items', sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False))
#     op.drop_constraint(None, 'items', type_='foreignkey')
#     op.create_foreign_key(op.f('items_tenant_id_fkey'), 'items', 'tenants', ['tenant_id'], ['id'])
#     op.drop_constraint('uq_item_name_per_client', 'items', type_='unique')
#     op.drop_index(op.f('ix_items_client_id'), table_name='items')
#     op.create_unique_constraint(op.f('uq_item_name_per_tenant'), 'items', ['name', 'tenant_id'], postgresql_nulls_not_distinct=False)
#     op.create_index(op.f('ix_items_tenant_id'), 'items', ['tenant_id'], unique=False)
#     op.drop_column('items', 'client_id')
#     op.drop_column('clients', 'role')
#     op.add_column('categories', sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True))
#     op.drop_constraint(None, 'categories', type_='foreignkey')
#     op.create_foreign_key(op.f('categories_tenant_id_fkey'), 'categories', 'tenants', ['tenant_id'], ['id'])
#     op.drop_column('categories', 'client_id')
#     op.add_column('brands', sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False))
#     op.drop_constraint(None, 'brands', type_='foreignkey')
#     op.create_foreign_key(op.f('brands_tenant_id_fkey'), 'brands', 'tenants', ['tenant_id'], ['id'])
#     op.drop_constraint('uq_brand_slug_per_client', 'brands', type_='unique')
#     op.create_unique_constraint(op.f('uq_brand_slug_per_tenant'), 'brands', ['tenant_id', 'slug'], postgresql_nulls_not_distinct=False)
#     op.drop_column('brands', 'client_id')
#     op.add_column('branches', sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False))
#     op.drop_constraint(None, 'branches', type_='foreignkey')
#     op.create_foreign_key(op.f('branches_tenant_id_fkey'), 'branches', 'tenants', ['tenant_id'], ['id'])
#     op.drop_column('branches', 'client_id')
#     op.create_table('order_items',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('order_items_item_id_fkey')),
#     sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('order_items_order_id_fkey')),
#     sa.PrimaryKeyConstraint('id', name=op.f('order_items_pkey'))
#     )
#     op.create_table('admin',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('partner_id', sa.INTEGER(), autoincrement=False, nullable=False),
#     sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
#     sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
#     sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
#     sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
#     sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('admin_partner_id_fkey')),
#     sa.PrimaryKeyConstraint('id', name=op.f('admin_pkey'))
#     )
#     op.create_index(op.f('ix_admin_email'), 'admin', ['email'], unique=True)
#     op.create_table('tenants',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
#     sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=False),
#     sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], name=op.f('tenants_admin_id_fkey')),
#     sa.PrimaryKeyConstraint('id', name=op.f('tenants_pkey'))
#     )
#     op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
#     op.create_table('customers',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
#     sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
#     sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
#     sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('branch_name', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('customers_branch_id_fkey')),
#     sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('customers_tenant_id_fkey')),
#     sa.PrimaryKeyConstraint('id', name=op.f('customers_pkey')),
#     sa.UniqueConstraint('phone', 'tenant_id', name=op.f('uq_customer_phone_per_tenant'), postgresql_include=[], postgresql_nulls_not_distinct=False)
#     )
#     op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
#     op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
#     op.create_table('orders',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('table_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('order_type', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('customer_name', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('customer_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
#     sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
#     sa.Column('total_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('orders_branch_id_fkey')),
#     sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name=op.f('orders_table_id_fkey')),
#     sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('orders_tenant_id_fkey')),
#     sa.PrimaryKeyConstraint('id', name=op.f('orders_pkey'))
#     )
#     op.create_table('inventory_items',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
#     sa.Column('row_category', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('stock_qty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
#     sa.Column('reorder_level', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
#     sa.Column('cost_per_unit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
#     sa.Column('vendor_name', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('vendor_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('last_restocked', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
#     sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('inventory_items_branch_id_fkey')),
#     sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('inventory_items_tenant_id_fkey')),
#     sa.PrimaryKeyConstraint('id', name=op.f('inventory_items_pkey'))
#     )
#     # ### end Alembic commands ###
