"""sync models

Revision ID: e31f32989ba0
Revises: 402449345b4d
Create Date: 2026-06-01 17:53:26.182972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e31f32989ba0'
down_revision: Union[str, Sequence[str], None] = '402449345b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'branch_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('staff', 'branch_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff', 'branch_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('categories', 'branch_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
