"""fix pricing

Revision ID: fe6fdab183cd
Revises: 1820438e66ab
Create Date: 2026-04-23 16:44:24.178122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe6fdab183cd'
down_revision: Union[str, Sequence[str], None] = '1820438e66ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_index(op.f('ix_customers_id'), table_name='customers')
#     op.drop_index(op.f('ix_customers_phone'), table_name='customers')
#     op.drop_table('customers')
#     op.drop_table('orders')
#     op.drop_table('order_items')
#     op.add_column('pricings', sa.Column('branch_id', sa.Integer(), nullable=True))
#     op.drop_constraint(op.f('unique_item_per_tenant'), 'pricings', type_='unique')
#     op.create_foreign_key(None, 'pricings', 'branches', ['branch_id'], ['id'])
#     op.alter_column('tables', 'shape',
#                existing_type=postgresql.ENUM('rectangular', 'round', 'square', 'oval', name='tableshape'),
#                type_=sa.Enum('rectangular', 'round', 'square', 'oval', name='tableshape', schema='public'),
#                existing_nullable=True)
#     # ### end Alembic commands ###
#     op.drop_table('order_items')
#     op.drop_table('orders')
#     op.add_column('orders', sa.Column('total_price', sa.Float(), nullable=True))
def upgrade() -> None:
    """Upgrade schema."""

    # ✅ Add branch_id to pricings
    op.add_column('pricings', sa.Column('branch_id', sa.Integer(), nullable=True))

    # ✅ Update constraint
    op.drop_constraint(op.f('unique_item_per_tenant'), 'pricings', type_='unique')

    # (optional: recreate with branch_id if needed)
    # op.create_unique_constraint(
    #     'unique_item_per_branch',
    #     'pricings',
    #     ['tenant_id', 'item_id', 'branch_id']
    # )

    op.create_foreign_key(
        None, 'pricings', 'branches',
        ['branch_id'], ['id']
    )

    # ✅ Fix enum schema issue
    op.alter_column(
        'tables',
        'shape',
        existing_type=postgresql.ENUM('rectangular', 'round', 'square', 'oval', name='tableshape'),
        type_=sa.Enum('rectangular', 'round', 'square', 'oval', name='tableshape', schema='public'),
        existing_nullable=True
    )

    # ✅ Add pricing field to orders (THIS is what you wanted)
    op.add_column('orders', sa.Column('total_price', sa.Float(), nullable=True))

# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('tables', 'shape',
#                existing_type=sa.Enum('rectangular', 'round', 'square', 'oval', name='tableshape', schema='public'),
#                type_=postgresql.ENUM('rectangular', 'round', 'square', 'oval', name='tableshape'),
#                existing_nullable=True)
#     op.drop_constraint(None, 'pricings', type_='foreignkey')
#     op.create_unique_constraint(op.f('unique_item_per_tenant'), 'pricings', ['tenant_id', 'item_id'], postgresql_nulls_not_distinct=False)
#     op.drop_column('pricings', 'branch_id')
#     op.create_table('order_items',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('order_items_item_id_fkey')),
#     sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('order_items_order_id_fkey')),
#     sa.PrimaryKeyConstraint('id', name=op.f('order_items_pkey'))
#     )
#     op.create_table('orders',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('table_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('order_type', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('customer_name', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('customer_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
#     sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('orders_branch_id_fkey')),
#     sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name=op.f('orders_table_id_fkey')),
#     sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('orders_tenant_id_fkey')),
#     sa.PrimaryKeyConstraint('id', name=op.f('orders_pkey'))
#     )
#     op.create_table('customers',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
#     sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
#     sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
#     sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('branch_name', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('customers_branch_id_fkey')),
#     sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('customers_tenant_id_fkey')),
#     sa.PrimaryKeyConstraint('id', name=op.f('customers_pkey')),
#     sa.UniqueConstraint('phone', 'tenant_id', name=op.f('uq_customer_phone_per_tenant'), postgresql_include=[], postgresql_nulls_not_distinct=False)
#     )
#     op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
#     op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
#     # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""

    op.drop_column('orders', 'total_price')

    op.alter_column(
        'tables',
        'shape',
        existing_type=sa.Enum('rectangular', 'round', 'square', 'oval', name='tableshape', schema='public'),
        type_=postgresql.ENUM('rectangular', 'round', 'square', 'oval', name='tableshape'),
        existing_nullable=True
    )

    op.drop_constraint(None, 'pricings', type_='foreignkey')

    op.create_unique_constraint(
        op.f('unique_item_per_tenant'),
        'pricings',
        ['tenant_id', 'item_id']
    )

    op.drop_column('pricings', 'branch_id')